### ISSUE TITLE
@dash4/plugin-code-coverage: All versions of https-proxy-agent are vulnerable to Machine-In-The-Middle.

### ISSUE THREAD

**Issue by aalibaabaa** [smollweide/dash4#5]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the motivation?

All versions of https-proxy-agent are vulnerable to Machine-In-The-Middle. The package fails to enforce TLS on the socket if the proxy server responds the to the request with a HTTP status different than 200. This allows an attacker with access to the proxy server to intercept unencrypted communications, which may include sensitive information such as credentials.

Remediation
Upgrade to version 3.0.0 or later.

See: https://www.npmjs.com/advisories/1184

## Please tell us about your environment

<pre><code>
@dash4/plugin-code-coverage: 0.5.1

</code></pre>

**Comment by smollweide** [comment]
This is an upstream issue, dash4 has no direct dependency on this package: npm/make-fetch-happen#6

**Comment by smollweide** [comment]
Hi @aalibaabaa,
please update to 0.7.0

**Comment by aalibaabaa** [comment]
Top! Now it works again. Thanks.
